/**
 * Copyright (c) Greater London Authority, 2016.
 *
 * This source code is licensed under the Open Government Licence 3.0.
 *
 * http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
 */
package uk.gov.london.ops.report;

import com.fasterxml.jackson.annotation.JsonIgnore;
import uk.gov.london.ops.file.AttachmentFile;
import uk.gov.london.ops.framework.jpa.Join;
import uk.gov.london.ops.framework.jpa.JoinData;

import javax.persistence.*;
import java.time.OffsetDateTime;

/**
 * Represents a report generated by a user
 * Created by Rob Bettison on 19/07/2018.
 */
@Entity(name="user_report")
public class UserReport {

    public enum Status { inProgress, noResults, Complete, Failed }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_report_seq_gen")
    @SequenceGenerator(name = "user_report_seq_gen", sequenceName = "user_report_seq", initialValue = 1000, allocationSize = 1)
    private Integer id;

    @Column(name = "name")
    private String name;

    @Column(name = "username")
    private String username;

    @Column(name = "start_time")
    private OffsetDateTime startTime;

    @Column(name = "end_time")
    private OffsetDateTime endTime;

    @Column(name = "status")
    @Enumerated(EnumType.STRING)
    private Status status;

    @Column(name = "report_id")
    private Integer reportId;

    @JsonIgnore
    @JoinData(joinType = Join.JoinType.OneToOne, sourceColumn = "attachment_file_id", targetColumn = "id", targetTable = "file", comment = "")
    @OneToOne(cascade = CascadeType.ALL)
    private AttachmentFile attachmentFile;

    public UserReport() {

    }

    public UserReport(String username, OffsetDateTime startTime, Status status, AttachmentFile attachmentFile, Integer reportId, String name) {
        this.username = username;
        this.startTime = startTime;
        this.status = status;
        this.attachmentFile = attachmentFile;
        this.reportId = reportId;
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return username;
    }

    public void setUserName(String username) {
        this.username = username;
    }

    public OffsetDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(OffsetDateTime startTime) {
        this.startTime = startTime;
    }

    public OffsetDateTime getEndTime() {
        return endTime;
    }

    public void setEndTime(OffsetDateTime endTime) {
        this.endTime = endTime;
    }

    public AttachmentFile getAttachmentFile() {
        return attachmentFile;
    }

    public void setAttachmentFile(AttachmentFile attachmentFile) {
        this.attachmentFile = attachmentFile;
    }


    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Integer getReportId() {
        return reportId;
    }

    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    @Transient
    public Integer getAttachmentFileId() {
        if(attachmentFile != null) {
            return attachmentFile.getId();
        }
        return null;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
